### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c sh -c 'curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg'" did not complete successfully: exit code: 7

### ISSUE THREAD

**Issue by xuduoudo0505** [migeran/holoocean_tools#2]
when i input ./build_all_from_src.sh
it turn out

=> ERROR [19/49] RUN sh -c 'curl -sSL https://raw.githubusercontent.com/  0.1s 
------                                                                          
 > [19/49] RUN sh -c 'curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg':
0.100 curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 48 ms: Connection refused
------
Dockerfile:27
--------------------
  25 |     
  26 |     RUN apt update && apt install -y curl gnupg lsb-release
  27 | >>> RUN sh -c 'curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg'
  28 |     RUN sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null'
  29 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c sh -c 'curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg'" did not complete successfully: exit code: 7

**Comment by kisg** [comment]
This seems like a network connection issue during the docker build.

**Comment by xuduoudo0505** [comment]
> This seems like a network connection issue during the docker build.这似乎是Docker构建过程中的网络连接问题。

i  had already solved this problem.
but i meet another problem 
"UID changed to: 0
User name changed to: root
usermod: user 'root' already exists
chown: cannot access '/home/root': No such file or directory
Fixing inconsistent case in filenames."

**Comment by kisg** [comment]
This means that you are running things as root. You should not do that. Run them as your local user. You will have to add your user to the docker group. These issues are not related to holoocean_ros.

**Comment by xuduoudo0505** [comment]
> This means that you are running things as root. You should not do that. Run them as your local user. You will have to add your user to the docker group. These issues are not related to holoocean_ros.

thanks for reply

forgive me,i meet the problem again

when i run "./build_all_from_src.sh",the terminal show 
"[3039/3039] UnrealBuildTool.exe UE4Editor-Linux-Debug.target
Total time in Local executor: 2766.98 seconds
Total execution time: 2902.39 seconds
UID changed to: 1000
User name changed to: zb
Error: [Errno 13] Permission denied: '/holoocean/holooceanvenv'"

could you please tell me  the reason for the error and what should i do next?
best wishes for you

**Comment by kisg** [comment]
Try this on your host:

```
sudo chown -R zb:zb /path/to/holoocean
```

Where /path/to/holoocean is the folder where you checked out the source repositories.

**Comment by xuduoudo0505** [comment]
> Try this on your host:
> 
> ```
> sudo chown -R zb:zb /path/to/holoocean
> ```
> 
> Where /path/to/holoocean is the folder where you checked out the source repositories.

Thank you again for your reply，that's useful 
but when i run './build_all_from_src.sh holoocean_sim_build'
the terminal show in the last

'Successfully installed sonar-data-processor-1.0
Starting >>> hoveringauv_thruster_control
Starting >>> py_ros2_holoocean
Starting >>> sonar_data_processor
Finished <<< py_ros2_holoocean [1.65s]
Finished <<< hoveringauv_thruster_control [7.20s]
[9.427s] WARNING:colcon.colcon_cmake.task.cmake.build:Could not run installation step for package 'sonar_data_processor' because it has no 'install' target
Finished <<< sonar_data_processor [7.80s]
Summary: 3 packages finished [8.76s]'

I don't know if this installation was successful.

and i try to run './run_holoocean_test.sh'
An error has occurred:
'Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/holoocean/holooceanvenv/lib/python3.10/site-packages/holoocean/holoocean.py", line 103, in make
    return HoloOceanEnvironment(**param_dict)
  File "/holoocean/holooceanvenv/lib/python3.10/site-packages/holoocean/environments.py", line 216, in __init__
    self._client.acquire(self._timeout)
  File "/holoocean/holooceanvenv/lib/python3.10/site-packages/holoocean/holooceanclient.py", line 101, in acquire
    self._get_semaphore_fn(self._semaphore2, timeout)
  File "/holoocean/holooceanvenv/lib/python3.10/site-packages/holoocean/holooceanclient.py", line 84, in posix_acquire_semaphore
    sem.acquire(timeout)
posix_ipc.BusyError: Semaphore is busy'

could please help me to figure out the problem,I would greatly appreciate it

**Comment by xuduoudo0505** [comment]
could you please do me a favor again to solve this problem, anything would be useful.
best wishes to you.

**Comment by Jayzhang2333** [comment]
Any solve on this last comment? I ran into the same problem
